# Generated by Django 4.1.6 on 2023-02-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_spirit_liquor_remove_liquor_cocktails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquor',
            name='spirit',
        ),
    ]
