# Generated by Django 4.1.6 on 2023-02-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_liquor_spirit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('B', 'Brandy'), ('G', 'Gin'), ('M', 'Mezcal'), ('R', 'Rum'), ('M', 'Mezcal'), ('T', 'Tequila'), ('V', 'Vodka')], default='B', max_length=1)),
                ('liquor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.liquor')),
            ],
        ),
    ]
